# This file is just a sample of the configurable properties provided by the project.
# All the values shown here are just the faults documented here: wiremock.org/docs/configuration
# Please read the official documentation and keep/set only the properties you need
#wm:
#  server:
#    port: 8080
#    mappingsFilesDir: src/test/resources
#    jetty:
#      containerThreads: 10
#      accepter: 2
#      acceptQueueSize: 100
#      headerBufferSize: 8192
#      asynchronousResponse: false
#      asynchronousThreads: 10
#    requestJournal:
#      disable: false
#      maxEntries: 100
#remote:
#  git:
#    uri: ssh://url-to-your-repo
#    hostname: hostname-from-the-uri
#    branch: target-branch, defaults to master
#    path-to-stub: path-to-stub (parent director for mappings and __files directory), defaults to root of repo
#    host-key: key-to-host-server
#    host-key-algorithm: ssh-rsa
#    private-key: private-key (\n separated value from your private key file, id_rsa)
